### ISSUE TITLE
Create better default styling if CSS is missing

### ISSUE THREAD

**Issue by mindok** [mindok/contex#27]
It is confusing when category labels etc don't show up because CSS styles are missing. Create some better default behaviour

**Comment by srowley** [comment]
In GGity I approach this by just inserting an embedded stylesheet by default. The user can specify no stylesheet if they want to use an external one. Here that could be something like `Plot.default_style(plot, false)` or `Plot.attributes(plot, default_style: false),` in which case nothing gets inserted.

This isn't in GGity master yet. I made it more complicated than it probably needs to be in order to support constructing styles via the API (a la ggplot2 themes), and that part is not yet ready. Implementing the simple "default or nothing" approach above is a lot more straightforward, and I can probably repackage what I have already done into a PR if you are interested.

**Comment by mindok** [comment]
Thanks @srowley - makes sense. I'm thinking of the following:
1. Just enough default styling that things don't disappear if no CSS added
2. Option to switch off default style
3. Try to organise default styles so that they are overridden if CSS is provided but default styles aren't switched off. I'm sure there are some specificity gotchas when combining embedded css with external, and I'm sure there different depending on browser...

**Comment by srowley** [comment]
With that in mind, the key constraint is that a given selector in the embedded style is always going to override the same selector in an external sheet. If the goal is to minimize the defaults and make it easy for them to be overridden even if the default is still on, I would think you can literally just insert:

```
    <style type="text/css">
      <![CDATA[
      text {
        fill: black
      }

      line {
        stroke: black
      }
      ]]>
    </style>
```
and all of the labels and tick-marks would show up. Any selector that uses a class (e.g. `exc-tick text`) in an external sheet would override that, so you don't have to make your external styles any more specific for them to override the default.

If that makes sense I'll send a PR; that's an easy one.

**Comment by mindok** [comment]
Perfect. That’s pretty well what I had in mind...
