### ISSUE TITLE
Version without timex

### ISSUE THREAD

**Issue by axelson** [mindok/contex#7]
I hesitate before filing this issue because it might be a little overbearing. But would it be possible to remove timex as a dependency? Because I use contex in an application that runs as an escript I have to workaround https://github.com/lau/tzdata/issues/24 and timex isn't really being used heavily in Contex. If it it too much work/not worth changing then feel free to close this.

**Comment by mindok** [comment]
Yeah I'm generally allergic to dependencies because situations like this happen... I was originally planning to pull Phoenix.HTML in to help with some of the rendering code but ended up coding it by hand for this very reason.

There are a few things I use Timex for, all of which are in TimeScale:
1. Calculating date diffs to figure out the right tick intervals.
2. Incrementing time intervals for the tick intervals.
3. Calculating conversion functions between time domains and graphics coordinate system (mostly diffs and adding intervals again)
4. Formatting (Lines 156-162 figure out the format, Line 251 executes it)

I think there may be a reasonably clean way to replace 1,2 & 3 using core elixir libraries without rewriting chunks of Timex but I may be wrong. It looks like Elixir's DateTime abstracts the timezone issue away via Calendar, so maybe that's a reasonable pathway, BUT it doesn't support adding time periods specified in units greater than a second. That doesn't work for adding months due to their variable size. 

Formatting just looks like fiddling around - localising the months is probably the only hard bit.

**Comment by axelson** [comment]
Hmmm, perhaps another approach could be to make timex an optional dependency. Then if my project doesn't use TimeScale it won't need timex.

Since an alternative to calculate the date diffs would probably be quite difficult due to the vagaries of the definition of time.

**Comment by mindok** [comment]
Nearly there... date diffs turned out to be not too bad - I pass it down to the core Elixir datetime libraries other than month & year - I have copied in 30-40 lines of Timex to handle that. I'll have to write quite a few tests around TimeScale at some point to check different time periods get handled correctly.

Formatting is quite complex. I'm going to use nimble_strftime - https://github.com/dashbitco/nimble_strftime - it has no run-time dependencies and will be moved into core Elixir in v1.11

**Comment by mindok** [comment]
ok - I've just pushed a commit without the Timex dependency. It takes out quite a few transitive dependencies - timex is pretty heavy. I'll spend a little more time later today testing & cleaning up.

**Comment by mindok** [comment]
test coverage in place, a few bugs fixed along the way, I'm calling this done :)

**Comment by axelson** [comment]
Thanks for this! :+1: on utilizing nimble_strftime
